//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinerGunBuilderCalculator {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_tooltips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_tooltips() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinerGunBuilderCalculator.Resource_tooltips", typeof(Resource_tooltips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Guides the projectile to the right. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_01_Guide_right {
            get {
                return ResourceManager.GetString("Item_01_Guide_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guides the projectile to the left. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_02_Guide_left {
            get {
                return ResourceManager.GetString("Item_02_Guide_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projectile damage by 1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_03_Add_1_damage {
            get {
                return ResourceManager.GetString("Item_03_Add_1_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projectile speed by 1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_04_Speed_up {
            get {
                return ResourceManager.GetString("Item_04_Speed_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Large spread to the left side. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_05_Spread_left {
            get {
                return ResourceManager.GetString("Item_05_Spread_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Large spread. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_06_Large_spread {
            get {
                return ResourceManager.GetString("Item_06_Large_spread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Large spread to the right side. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_07_Spread_right {
            get {
                return ResourceManager.GetString("Item_07_Spread_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Small spread. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_08_Small_spread {
            get {
                return ResourceManager.GetString("Item_08_Small_spread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projectile flies in a curve to the left. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_09_Curve_left {
            get {
                return ResourceManager.GetString("Item_09_Curve_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projectile flies in a random direction. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_10_Random_curve {
            get {
                return ResourceManager.GetString("Item_10_Random_curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projectile flies in a curve to the right. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_11_Curve_right {
            get {
                return ResourceManager.GetString("Item_11_Curve_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reduce projectile speed by half. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_12_Slow_down {
            get {
                return ResourceManager.GetString("Item_12_Slow_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chance of 33% for double damage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_13_Criticalx2 {
            get {
                return ResourceManager.GetString("Item_13_Criticalx2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chance of 4% for 10x damage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_14_Criticalx10 {
            get {
                return ResourceManager.GetString("Item_14_Criticalx10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Damage eigher times 0,1,1,1,1,1,1,1,1,1,2,3 or 4. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_15_Random_critical {
            get {
                return ResourceManager.GetString("Item_15_Random_critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Absorbs 20% of each damage from each projectile into its pool.And deals 10% of the pool&apos;s damage to each bullet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_16_Charge {
            get {
                return ResourceManager.GetString("Item_16_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The projectile returns after hit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_17_Return {
            get {
                return ResourceManager.GetString("Item_17_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bounce one time with random direction. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_18_Random_bounce {
            get {
                return ResourceManager.GetString("Item_18_Random_bounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projectiles rocochet off blocks. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_19_Richchet {
            get {
                return ResourceManager.GetString("Item_19_Richchet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doubles the lifetime of the projectile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_20_Double_lifetime {
            get {
                return ResourceManager.GetString("Item_20_Double_lifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Splits the projectile in two. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_21_Split_2_way {
            get {
                return ResourceManager.GetString("Item_21_Split_2_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Splits the projectile in three. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_22_Split_3_way {
            get {
                return ResourceManager.GetString("Item_22_Split_3_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double damage but random direction. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_23_Random_2_way {
            get {
                return ResourceManager.GetString("Item_23_Random_2_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Triple damage but random direction. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_24_Random_3_way {
            get {
                return ResourceManager.GetString("Item_24_Random_3_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If block destroyed,continue with bot of remaining damage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_25_Remaining_damage {
            get {
                return ResourceManager.GetString("Item_25_Remaining_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projectile pierces one block に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_26_Pierce {
            get {
                return ResourceManager.GetString("Item_26_Pierce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area damage in a circle but 4% less total damage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_27_Round_area {
            get {
                return ResourceManager.GetString("Item_27_Round_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area damage in a horizontal rectangle. 4% less total damage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_28_Rectangle_area {
            get {
                return ResourceManager.GetString("Item_28_Rectangle_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projectiles attract each other. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_29_Attraction {
            get {
                return ResourceManager.GetString("Item_29_Attraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projectiles align their diection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_30_Align_direction {
            get {
                return ResourceManager.GetString("Item_30_Align_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attraction to line in fron of ship. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_31_Align_to_ship {
            get {
                return ResourceManager.GetString("Item_31_Align_to_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add 1 projectle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_32_Add_projectile {
            get {
                return ResourceManager.GetString("Item_32_Add_projectile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After some distance projectile fly upwards. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_33_Fly_forward {
            get {
                return ResourceManager.GetString("Item_33_Fly_forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After some distance projectile fly sideways. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_34_Fly_sideways {
            get {
                return ResourceManager.GetString("Item_34_Fly_sideways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   30% more money when first passed sideways then on defaut direction. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_35_Money_crossing {
            get {
                return ResourceManager.GetString("Item_35_Money_crossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds the damage from the last time crossed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_36_Damage_crossing {
            get {
                return ResourceManager.GetString("Item_36_Damage_crossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds 100 damage to the projectild. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Item_700_Add_100_damage {
            get {
                return ResourceManager.GetString("Item_700_Add_100_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wall に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Parts_01_Wall {
            get {
                return ResourceManager.GetString("Parts_01_Wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projectile Ejector に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Parts_02_Ejector {
            get {
                return ResourceManager.GetString("Parts_02_Ejector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projectile generator. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Parts_03_ProjectileGenerator {
            get {
                return ResourceManager.GetString("Parts_03_ProjectileGenerator", resourceCulture);
            }
        }
    }
}
