//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinerGunBuilderCalculator {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_skilltree {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_skilltree() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinerGunBuilderCalculator.Resource_skilltree", typeof(Resource_skilltree).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Adds 5 damage for each item from the projectile generator to itself. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _00_07 {
            get {
                return ResourceManager.GetString("00_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds additional 30 damage to the projectile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _01_08 {
            get {
                return ResourceManager.GetString("01_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Higher multiplier of times 2.5. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _01_12 {
            get {
                return ResourceManager.GetString("01_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Higher multiplier of times 12 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _01_16 {
            get {
                return ResourceManager.GetString("01_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8x damage instead of 4x. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _02_07 {
            get {
                return ResourceManager.GetString("02_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Increased chance of 40% for damage multiplier. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _02_13 {
            get {
                return ResourceManager.GetString("02_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Increased chance of 6% for damage multiplier. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _02_15 {
            get {
                return ResourceManager.GetString("02_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Combines only 6 projectiles instead. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _02_17 {
            get {
                return ResourceManager.GetString("02_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds up to 60% more damage with bigger ejection curve angle. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _03_08 {
            get {
                return ResourceManager.GetString("03_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds +5 damage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _03_12 {
            get {
                return ResourceManager.GetString("03_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multipliers are instead 0,1,1,2 or 3. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _03_16 {
            get {
                return ResourceManager.GetString("03_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multipliers are instead 0,0,0,1,2,3 or 4. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _03_18 {
            get {
                return ResourceManager.GetString("03_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds up to 40% more damage with bigger ejection curve angle. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _04_05 {
            get {
                return ResourceManager.GetString("04_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds +5 damage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _04_11 {
            get {
                return ResourceManager.GetString("04_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Increase the speed thresholds to 1.2 to 1.3. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _04_17 {
            get {
                return ResourceManager.GetString("04_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds +20 additional damage for each in ship. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _05_00 {
            get {
                return ResourceManager.GetString("05_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds up to 40% more damage with bigger ejection curve angle. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _05_06 {
            get {
                return ResourceManager.GetString("05_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds +5 additional damage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _05_08 {
            get {
                return ResourceManager.GetString("05_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds +5 damage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _05_10 {
            get {
                return ResourceManager.GetString("05_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds up to 50% more damage with bigger ejection angle. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _06_11 {
            get {
                return ResourceManager.GetString("06_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds instead 30% of damage to following projectiles. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _06_13 {
            get {
                return ResourceManager.GetString("06_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds up to 60% more damage with bigger ejection angle. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _07_10 {
            get {
                return ResourceManager.GetString("07_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds up to 50% more damage with bigger ejection angle. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _07_12 {
            get {
                return ResourceManager.GetString("07_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Legendary items count as unused tile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _08_05 {
            get {
                return ResourceManager.GetString("08_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Higher damage multiplier of 4. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _08_07 {
            get {
                return ResourceManager.GetString("08_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Higher damage multiplier of 3. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _08_09 {
            get {
                return ResourceManager.GetString("08_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adds up to 25% more damage with bigger ejection angle. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _08_11 {
            get {
                return ResourceManager.GetString("08_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projectile direction guides count as unused tile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _09_04 {
            get {
                return ResourceManager.GetString("09_04", resourceCulture);
            }
        }
    }
}
